### ISSUE TITLE
Compiler options for compiling the code.

### ISSUE THREAD

**Issue by rishiba** [PacktPublishing/Modern-Cpp-Programming-Cookbook#1]
I am trying to compile the code of the 8th Chapter with the following command 

`$ g++-7 main.cpp  -std=c++17 `. I am getting a lot of errors. Can you please add a simple makefile for the code or reply with the command which will compile the code correctly.

Here is the error i get

$ g++-7 main.cpp  -std=c++17 
In file included from main.cpp:2:0:
recipe_8_02.h: In function ‘void recipe_8_02::func1()’:
recipe_8_02.h:15:41: error: no matching function for call to ‘std::exception::exception(const char [12])’
       throw std::exception("exception 1");
                                         ^
In file included from /usr/include/c++/7/exception:38:0,
                 from /usr/include/c++/7/ios:39,
                 from /usr/include/c++/7/ostream:38,
                 from /usr/include/c++/7/iostream:39,
                 from recipe_8_01.h:3,
                 from main.cpp:1:
/usr/include/c++/7/bits/exception.h:63:5: note: candidate: std::exception::exception()
     exception() _GLIBCXX_USE_NOEXCEPT { }
     ^~~~~~~~~
/usr/include/c++/7/bits/exception.h:63:5: note:   candidate expects 0 arguments, 1 provided
/usr/include/c++/7/bits/exception.h:60:9: note: candidate: constexpr std::exception::exception(const std::exception&)
   class exception
         ^~~~~~~~~
/usr/include/c++/7/bits/exception.h:60:9: note:   no known conversion for argument 1 from ‘const char [12]’ to ‘const std::exception&’
In file included from main.cpp:2:0:
recipe_8_02.h: In function ‘void recipe_8_02::func2()’:
recipe_8_02.h:20:41: error: no matching function for call to ‘std::exception::exception(const char [12])’
       throw std::exception("exception 2");
                                         ^
In file included from /usr/include/c++/7/exception:38:0,
                 from /usr/include/c++/7/ios:39,
                 from /usr/include/c++/7/ostream:38,
                 from /usr/include/c++/7/iostream:39,
                 from recipe_8_01.h:3,
                 from main.cpp:1:
/usr/include/c++/7/bits/exception.h:63:5: note: candidate: std::exception::exception()
     exception() _GLIBCXX_USE_NOEXCEPT { }
     ^~~~~~~~~
/usr/include/c++/7/bits/exception.h:63:5: note:   candidate expects 0 arguments, 1 provided
/usr/include/c++/7/bits/exception.h:60:9: note: candidate: constexpr std::exception::exception(const std::exception&)
   class exception
         ^~~~~~~~~
/usr/include/c++/7/bits/exception.h:60:9: note:   no known conversion for argument 1 from ‘const char [12]’ to ‘const std::exception&’
In file included from main.cpp:5:0:
recipe_8_05.h: In function ‘void recipe_8_05::execute()’:
recipe_8_05.h:76:12: error: ‘generate’ is not a member of ‘std’
       std::generate(std::begin(seed_data), std::end(seed_data), std::ref(rd));
            ^~~~~~~~
recipe_8_05.h:76:12: note: suggested alternative: ‘negate’
       std::generate(std::begin(seed_data), std::end(seed_data), std::ref(rd));
            ^~~~~~~~
            negate
In file included from main.cpp:8:0:
recipe_8_08.h: In function ‘std::vector<int, std::allocator<int> > recipe_8_08::generate_random()’:
recipe_8_08.h:55:12: error: ‘generate’ is not a member of ‘std’
       std::generate(std::begin(numbers), std::end(numbers), [&dis, &generator] {return dis(generator); });
            ^~~~~~~~
recipe_8_08.h:55:12: note: suggested alternative: ‘negate’
       std::generate(std::begin(numbers), std::end(numbers), [&dis, &generator] {return dis(generator); });
            ^~~~~~~~
            negate
In file included from main.cpp:9:0:
recipe_8_09.h: In static member function ‘static Time recipe_8_09::perf_timer<Time, Clock>::duration(F&&, Args ...)’:
recipe_8_09.h:21:15: error: ‘invoke’ is not a member of ‘std’
          std::invoke(std::forward<F>(f), std::forward<Args>(args)...);
               ^~~~~~
recipe_8_09.h:21:15: note: suggested alternative: ‘__invoke’
          std::invoke(std::forward<F>(f), std::forward<Args>(args)...);
               ^~~~~~
               __invoke
In file included from main.cpp:10:0:
recipe_8_10.h: In static member function ‘static Time recipe_8_10::perf_timer<Time, Clock>::duration(F&&, Args ...)’:
recipe_8_10.h:21:15: error: ‘invoke’ is not a member of ‘std’
          std::invoke(std::forward<F>(f), std::forward<Args>(args)...);
               ^~~~~~
recipe_8_10.h:21:15: note: suggested alternative: ‘__invoke’
          std::invoke(std::forward<F>(f), std::forward<Args>(args)...);
               ^~~~~~
               __invoke
In file included from main.cpp:3:0:
recipe_8_03.h: In instantiation of ‘void recipe_8_03::move_between(recipe_8_03::container<T>&, recipe_8_03::container<T>&, T) [with T = int]’:
recipe_8_03.h:141:73:   required from here
recipe_8_03.h:95:21: error: cannot convert ‘std::vector<int, std::allocator<int> >::iterator {aka __gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > >}’ to ‘const char*’ for argument ‘1’ to ‘int remove(const char*)’
          std::remove(c1.data.begin(), c1.data.end(), value),
          ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by rishiba** [comment]
It looks like that the code given in the repo is checked using VC++ only and is not supported by g++. See https://stackoverflow.com/questions/28640553/exception-class-with-a-char-constructor

**Comment by ManikandanKurup-Packt** [comment]
Please reopen the issue if the issue is still unresolved
